/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import mcacisi.Student;

/**
 *
 * @author Mcacisi Sithole
 */
public class ListDisplayer extends javax.swing.JFrame {

    /**
     * Creates new form ListDisplayer
     * @param arrStudent
     */
    public ListDisplayer(ArrayList<Student> arrStudent) {
        initComponents();
        
        StringBuilder ms = new StringBuilder();
        ms.append("STUDENTNO\t"+"INITIALS\t"+"SURNAME\t"+"MODULE\t"+"\t"+"MARK1\t"+"MARK2\t"+"MARK3"+"\t"+"TOTAL\t"+"EXAM ADMISSION\n");
        ms.append("________________________________________________________________________________________________________________________________\n");
        
        for(Student s : arrStudent){
            ms.append(s.getStudNo()).append("\t")
                      .append(s.getInitials()).append("\t")
                      .append(s.getSurname()).append("\t")
                      .append(s.getModule()).append("\t")
                      .append(s.getMark1()).append("\t")
                      .append(s.getMark2()).append("\t")
                      .append(s.getMark3()).append("\t")
                      .append(s.getFinalMark()).append("%").append("\t")
                      .append(s.getAdmission()).append("\n");
        }
        jTextArea1.setText(ms.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDisplay = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDisplay.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDisplay.setText("STUDENT LIST DISPLAYER");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 995, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDisplay)
                .addGap(393, 393, 393))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblDisplay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblDisplay;
    // End of variables declaration//GEN-END:variables
}
